theme: minima
title: Ivo's Graphics Blog
description: My personal blog (mostly about computer graphics).
plugins:
  - jekyll-seo-tag
disqus:
  shortname: ivokabel
google_analytics: UA-119530039-1
github_username: ivokabel
linkedin_username: ivopavlik
facebook_username: Ivokabel
show_excerpts: true
